### ISSUE TITLE
是不是少了个依赖：lxml？

### ISSUE THREAD

**Issue by Liber1917** [Neboer/ipgw-py-manager#3]
我的环境是gitpod，应该是redhat下的
报错：
Traceback (most recent call last):
  File "/home/gitpod/.pyenv/versions/3.12.0/bin/ipgw", line 33, in <module>
    sys.exit(load_entry_point('NEU-ipgw-manager==3.0', 'console_scripts', 'ipgw')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gitpod/.pyenv/versions/3.12.0/lib/python3.12/site-packages/ipgw/cli/ipgw.py", line 37, in main
    main_ipgw = IPGW()
                ^^^^^^
  File "/home/gitpod/.pyenv/versions/3.12.0/lib/python3.12/site-packages/ipgw/core/ipgw.py", line 15, in __init__
    self.union_auth_page = SSO_prepare(self.sess)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gitpod/.pyenv/versions/3.12.0/lib/python3.12/site-packages/ipgw/core/api/SSO.py", line 28, in SSO_prepare
    page_soup = BeautifulSoup(session.get(target).text, 'lxml')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/bs4/__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

**Comment by Neboer** [comment]
lxml可以用pip install lxml的方式安装，不过已经包含在pip安装脚本里了。请问您是怎么安装的本程序？

**Comment by Liber1917** [comment]
在gitpod 上使用clone

**Comment by Neboer** [comment]
用Python pip可以安装吗？直接pip install NEU-ipgw-manager

**Comment by Liber1917** [comment]
直接安装好像少依赖

**Comment by Neboer** [comment]
已收到反馈，未来的版本里会考虑把lxml依赖去掉。

**Comment by Neboer** [comment]
在新版本中，lxml已经不再是必须的依赖，我们使用更易于安装的html.parser代替原来的lxml，解决了此问题。
